### ISSUE TITLE
Exploring opportunity for possible collaboration on tiling program for underground utilities

### ISSUE THREAD

**Issue by arjan-odedra** [Gaia3D/mago-3d-tiler#13]
**Issue Description:**

We are exploring the potential of utilizing Mago3D Tiler for generating 3D tiles to represent underground utilities. Our specific use case involves incorporating depth as a parameter to organize lines under groups and using diameter to create lines of various sizes. However, upon exploring Mago3D Tiler, we haven't discovered a workflow that directly supports this use case.

**Proposed Solution:**

We propose initiating a discussion within the Mago3D Tiler community to explore potential solutions or workflows that could accommodate the representation of underground utilities in 3D tiles. This could involve incorporating depth and diameter parameters into the tiling process or exploring alternative methods to achieve the desired representation.

**Points for Discussion:**

1. Is there an existing workflow or feature within Mago3D Tiler that supports the representation of underground utilities?
2. How can depth and diameter parameters be integrated into the tiling process to accurately represent underground structures?
3. Are there any alternative approaches or plugins/extensions that could facilitate the creation of 3D tiles for underground utilities within Mago3D Tiler?
4. What are the best practices or recommended strategies for handling complex 3D tiling scenarios like underground infrastructure representation?

**Additional Context:**

We believe that addressing the representation of underground utilities in 3D tiles within Mago3D Tiler could greatly enhance its utility for urban planning, infrastructure management, and other related applications. Your insights and contributions to this discussion would be greatly appreciated.

**Note:** At [https://www.nascentinfo.com/](url) we have team of good java developers who can get involved in this discussions and hopefully will work on some great feature enhancement for Mago3D Tiler together so feel free to provide any additional information or insights related to this topic. Let's collaborate to find an effective solution within the Mago3D Tiler ecosystem. 

--- 

Looking forward to your feedback and contributions to this discussion

**Comment by shire75** [comment]
Hello, @arjan-odedra .

Thank you for your interest.

As long as the data of your underground utilities is in a 3D model format that mago 3dTiler can accept, there should be no problem to make it into 3D Tiles.

In fact, we have worked and are still working on projects to create Cesium-based digital twins of underground utilities using 3DS and obj files.

The reason why mago 3DTiler can't convert your underground utilities data to 3D Tiles is not because it is about 'underground utility', but because mago 3dTiler doesn't support the format/specification of the file containing the underground utility information.

In your case, based on what you wrote (depth and diameter), it seems to be a 2-dimensional blueprint. We see this case as not an 'underground utilities' case, but one of general cases of creating a 3-dimensional object from a combination of 2-dimensional geometric/spatial information and attributes.

What I mean by the combination of two-dimensional geometry/geospatial information and attributes is, for example, this.
One of mago 3dTiler's features, SHP to 3D Tiles, also combines two-dimensional spatial information (building horizontal cross-section polygon) with attributes (height) to create a three-dimensional object through the process of extrusion.
Creating a two-dimensional cross-sectional shape by rotating it by a certain angle around a certain axis is another example of combining two-dimensional geometric information with attributes to create a three-dimensional object (like a donut).

In the future, we plan to extend the interface to implement the ability to convert more common two-dimensional geometry/spatial information + attributes combinations into 3D Tiles.

Below are the answers to the four discussions you presented.

1. Is there an existing workflow or feature within Mago3D Tiler that supports the representation of underground utilities?
: If files of the underground utilities is in a format supported by mago 3dTiler, then yes, otherwise no.
2. How can depth and diameter parameters be integrated into the tiling process to accurately represent underground structures?
: To break down what I said above into something more concrete, you can implement a process that takes a combination of start/end point location + start/end point elevation + diameter and turns it into a cylinder.
3. Are there any alternative approaches or plugins/extensions that could facilitate the creation of 3D tiles for underground utilities within Mago3D Tiler?
: To answer in principle, there is no other approach. As mentioned, we are planning to implement this functionality ourselves (we could use some open source library that can read the input file format).
4. What are the best practices or recommended strategies for handling complex 3D tiling scenarios like underground infrastructure representation?
: It's too conceptual and broad to give a simple answer. The need to convert underground utilities to 3D Tiles arises in a wide variety of scenarios and involves a wide variety of data formats.

If you have any other questions, please feel free to reach out.

Thank you.
